=== dcos/dcos-ui/schema/mesos/state-summary.json
{
    "$schema": "http://json-schema.org/draft-04/schema",
    "id": "http://schema.mesos/state-01/summary",
    "title": "Mesos State Summary",
    "type": "object",
    "properties" : {
        "cluster": {
            "title": "Cluster name",
            "type": "string"
        },
        "frameworks": {
            "title": "Active frameworks",
            "description": "A list of all frameworks currently running.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "title": "Framework ID",
                        "type": "string"
                    },
                    "name": {
                        "title": "Framework Name",
                        "type": "string"
                    },
                    "offered_resources": {
                        "title": "Resources offered to framework",
                        "type": "object",
                        "properties": {
                            "cpus": {
                                "type": "number"
                            },
                            "disk": {
                                "type": "number"
                            },
                            "mem": {
                                "type": "number"
                            }
                        },
                        "required": ["cpus", "disk", "mem"]
                    },
                    "used_resources": {
                        "title": "Resources used by framework",
                        "type": "object",
                        "properties": {
                            "cpus": {
                                "type": "number"
                            },
                            "disk": {
                                "type": "number"
                            },
                            "mem": {
                                "type": "number"
                            }
                        },
                        "required": ["cpus", "disk", "mem"]
                    },
                    "slave_ids": {
                        "title": "Slave IDs",
                        "description": "A list of slave ids in which this framework is running in.",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "TASK_STAGING": {
                        "title": "A sum of staging tasks.",
                        "type": "integer"
                    },
                    "TASK_STARTING": {
                        "title": "A sum of starting tasks.",
                        "type": "integer"
                    },
                    "TASK_RUNNING": {
                        "title": "A sum of running tasks.",
                        "type": "integer"
                    },
                    "TASK_FINISHED": {
                        "title": "A sum of finished tasks.",
                        "type": "integer"
                    },
                    "TASK_KILLED": {
                        "title": "A sum of killed tasks.",
                        "type": "integer"
                    },
                    "TASK_FAILED": {
                        "title": "A sum of failed tasks.",
                        "type": "integer"
                    },
                    "TASK_LOST": {
                        "title": "A sum of lost tasks.",
                        "type": "integer"
                    },
                    "TASK_ERROR": {
                        "title": "A sum of errored tasks.",
                        "type": "integer"
                    },
                    "webui_url": {
                        "title": "Framework's URL endpoint",
                        "type": "string"
                    }
                },
                "required": [
                    "id",
                    "name",
                    "offered_resources",
                    "used_resources",
                    "slave_ids",
                    "webui_url",
                    "TASK_STAGING",
                    "TASK_STARTING",
                    "TASK_RUNNING",
                    "TASK_FINISHED",
                    "TASK_KILLED",
                    "TASK_FAILED",
                    "TASK_LOST",
                    "TASK_ERROR"
                ]
            }
        },
        "hostname": {
            "title": "Hostname of cluster",
            "type": "string"
        },
        "slaves": {
            "title": "Active slaves",
            "description": "A list of all slaves in the cluster.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "active": {
                        "title": "Wether the slave is active or not",
                        "type": "boolean"
                    },
                    "attributes": {
                        "title": "Any slave attributes",
                        "type": "object"
                    },
                    "hostname": {
                        "title": "Hostname of slave",
                        "type": "string"
                    },
                    "id": {
                        "title": "Slave ID",
                        "type": "string"
                    },
                    "resources": {
                        "title": "Resources available in slave",
                        "type": "object",
                        "properties": {
                            "cpus": {
                                "type": "number"
                            },
                            "disk": {
                                "type": "number"
                            },
                            "mem": {
                                "type": "number"
                            }
                        },
                        "required": ["cpus", "disk", "mem"]
                    },
                    "used_resources": {
                        "title": "Used resources in slave",
                        "type": "object",
                        "properties": {
                            "cpus": {
                                "type": "number"
                            },
                            "disk": {
                                "type": "number"
                            },
                            "mem": {
                                "type": "number"
                            }
                        },
                        "required": ["cpus", "disk", "mem"]
                    },
                    "TASK_STAGING": {
                        "title": "A sum of staging tasks.",
                        "type": "integer"
                    },
                    "TASK_STARTING": {
                        "title": "A sum of starting tasks.",
                        "type": "integer"
                    },
                    "TASK_RUNNING": {
                        "title": "A sum of running tasks.",
                        "type": "integer"
                    },
                    "TASK_FINISHED": {
                        "title": "A sum of finished tasks.",
                        "type": "integer"
                    },
                    "TASK_KILLED": {
                        "title": "A sum of killed tasks.",
                        "type": "integer"
                    },
                    "TASK_FAILED": {
                        "title": "A sum of failed tasks.",
                        "type": "integer"
                    },
                    "TASK_LOST": {
                        "title": "A sum of lost tasks.",
                        "type": "integer"
                    },
                    "TASK_ERROR": {
                        "title": "A sum of errored tasks.",
                        "type": "integer"
                    }
                },
                "required": [
                    "active",
                    "attributes",
                    "hostname",
                    "id",
                    "resources",
                    "used_resources",
                    "TASK_STAGING",
                    "TASK_STARTING",
                    "TASK_RUNNING",
                    "TASK_FINISHED",
                    "TASK_KILLED",
                    "TASK_FAILED",
                    "TASK_LOST",
                    "TASK_ERROR"
                ]
            }
        }
    },
    "required": [
        "cluster",
        "frameworks",
        "hostname",
        "slaves"
    ]
}

=== dcos/dcos-ui/tests/_fixtures/1-app-for-each-health/summary.json
{
  "cluster": "Vagrant_SingleNode",
  "frameworks": [
    {
      "TASK_ERROR": 0,
      "TASK_FAILED": 0,
      "TASK_FINISHED": 22,
      "TASK_KILLED": 0,
      "TASK_LOST": 0,
      "TASK_RUNNING": 1,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "hostname": "dcos-01",
      "id": "20150827-210452-1695027628-5050-1445-0000",
      "name": "cassandra-healthy",
      "offered_resources": {
        "cpus": 0,
        "disk": 0,
        "mem": 0
      },
      "pid": "scheduler-88e0ffb7-5d54-4bc4-984b-e546d4b1ebb1@172.17.8.101:47277",
      "slave_ids": [
        "20151002-000353-1695027628-5050-1177-S0"
      ],
      "used_resources": {
        "cpus": 0.1,
        "disk": 0,
        "mem": 16,
        "ports": "[10000-10000]"
      },
      "webui_url": "http://$($MESOS_IP_DISCOVERY_COMMAND):8080"
    },
    {
      "TASK_ERROR": 0,
      "TASK_FAILED": 0,
      "TASK_FINISHED": 22,
      "TASK_KILLED": 0,
      "TASK_LOST": 0,
      "TASK_RUNNING": 1,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "hostname": "dcos-01",
      "id": "20150827-210452-1695027628-5050-1445-0000",
      "name": "cassandra-unhealthy",
      "offered_resources": {
        "cpus": 0,
        "disk": 0,
        "mem": 0
      },
      "pid": "scheduler-88e0ffb7-5d54-4bc4-984b-e546d4b1ebb1@172.17.8.101:47277",
      "slave_ids": [
        "20151002-000353-1695027628-5050-1177-S0"
      ],
      "used_resources": {
        "cpus": 0.1,
        "disk": 0,
        "mem": 16,
        "ports": "[10000-10000]"
      },
      "webui_url": "http://$($MESOS_IP_DISCOVERY_COMMAND):8080"
    },
    {
      "TASK_ERROR": 0,
      "TASK_FAILED": 0,
      "TASK_FINISHED": 22,
      "TASK_KILLED": 0,
      "TASK_LOST": 0,
      "TASK_RUNNING": 1,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "hostname": "dcos-01",
      "id": "20150827-210452-1695027628-5050-1445-0000",
      "name": "cassandra-na",
      "offered_resources": {
        "cpus": 0,
        "disk": 0,
        "mem": 0
      },
      "pid": "scheduler-88e0ffb7-5d54-4bc4-984b-e546d4b1ebb1@172.17.8.101:47277",
      "slave_ids": [
        "20151002-000353-1695027628-5050-1177-S0"
      ],
      "used_resources": {
        "cpus": 0.1,
        "disk": 0,
        "mem": 16,
        "ports": "[10000-10000]"
      },
      "webui_url": "http://$($MESOS_IP_DISCOVERY_COMMAND):8080"
    },
    {
      "TASK_ERROR": 0,
      "TASK_FAILED": 0,
      "TASK_FINISHED": 22,
      "TASK_KILLED": 0,
      "TASK_LOST": 0,
      "TASK_RUNNING": 1,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "hostname": "dcos-01",
      "id": "20150827-210452-1695027628-5050-1445-0000",
      "name": "cassandra-idle",
      "offered_resources": {
        "cpus": 0,
        "disk": 0,
        "mem": 0
      },
      "pid": "scheduler-88e0ffb7-5d54-4bc4-984b-e546d4b1ebb1@172.17.8.101:47277",
      "slave_ids": [
        "20151002-000353-1695027628-5050-1177-S0"
      ],
      "used_resources": {
        "cpus": 0.1,
        "disk": 0,
        "mem": 16,
        "ports": "[10000-10000]"
      },
      "webui_url": "http://$($MESOS_IP_DISCOVERY_COMMAND):8080"
    }
  ],
  "hostname": "172.17.8.101",
  "slaves": [
    {
      "TASK_ERROR": 0,
      "TASK_FAILED": 0,
      "TASK_FINISHED": 22,
      "TASK_KILLED": 0,
      "TASK_LOST": 0,
      "TASK_RUNNING": 1,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "active": true,
      "attributes": {
        
      },
      "framework_ids": [
        "20150827-210452-1695027628-5050-1445-0000"
      ],
      "hostname": "dcos-01",
      "id": "20151002-000353-1695027628-5050-1177-S0",
      "offered_resources": {
        "cpus": 0,
        "disk": 0,
        "mem": 0
      },
      "pid": "slave(1)@172.17.8.101:5051",
      "registered_time": 1443995289.19971,
      "reregistered_time": 1443995289.19981,
      "reserved_resources": {
        
      },
      "resources": {
        "cpus": 4,
        "disk": 10823,
        "mem": 2933,
        "ports": "[1025-2180, 2182-3887, 3889-5049, 5052-8079, 8082-8180, 8182-32000]"
      },
      "unreserved_resources": {
        "cpus": 4,
        "disk": 10823,
        "mem": 2933,
        "ports": "[1025-2180, 2182-3887, 3889-5049, 5052-8079, 8082-8180, 8182-32000]"
      },
      "used_resources": {
        "cpus": 0.1,
        "disk": 0,
        "mem": 16,
        "ports": "[10000-10000]"
      }
    }
  ]
}

=== dcos/dcos-ui/tests/_fixtures/healthy-tasks-in-mesos-and-marathon/summary.json
{
  "hostname": "10.0.4.58",
  "cluster": "frontend-us-west-2-ht0quvq7kr",
  "slaves": [
    {
      "id": "74f1836b-6784-4030-816e-aacbdd45ff57-S1",
      "pid": "slave(1)@10.0.2.121:5051",
      "hostname": "10.0.2.121",
      "registered_time": 1483977267.25785,
      "resources": {
        "disk": 35577,
        "mem": 14018,
        "gpus": 0,
        "cpus": 4,
        "ports": "[1025-2180, 2182-3887, 3889-5049, 5052-8079, 8082-8180, 8182-32000]"
      },
      "used_resources": {
        "disk": 5000,
        "mem": 3822,
        "gpus": 0,
        "cpus": 2.51,
        "ports": "[1025-1025, 9234-9234, 24348-24349, 29557-29557]"
      },
      "offered_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "reserved_resources": {
        "confluent-kafka-role": {
          "disk": 5000,
          "mem": 2560,
          "gpus": 0,
          "cpus": 1.5,
          "ports": "[1025-1025, 9234-9234]"
        }
      },
      "unreserved_resources": {
        "disk": 30577,
        "mem": 11458,
        "gpus": 0,
        "cpus": 2.5,
        "ports": "[1026-2180, 2182-3887, 3889-5049, 5052-8079, 8082-8180, 8182-9233, 9235-32000]"
      },
      "attributes": {},
      "active": true,
      "version": "1.2.0",
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "TASK_RUNNING": 3,
      "TASK_KILLING": 0,
      "TASK_FINISHED": 0,
      "TASK_KILLED": 0,
      "TASK_FAILED": 0,
      "TASK_LOST": 0,
      "TASK_ERROR": 0,
      "framework_ids": [
        "74f1836b-6784-4030-816e-aacbdd45ff57-0001",
        "74f1836b-6784-4030-816e-aacbdd45ff57-0002"
      ]
    },
    {
      "id": "74f1836b-6784-4030-816e-aacbdd45ff57-S0",
      "pid": "slave(1)@10.0.6.244:5051",
      "hostname": "10.0.6.244",
      "registered_time": 1483976648.5341,
      "resources": {
        "disk": 35577,
        "mem": 14018,
        "gpus": 0,
        "cpus": 4,
        "ports": "[1-21, 23-5050, 5052-32000]"
      },
      "used_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "offered_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "reserved_resources": {
        "slave_public": {
          "disk": 35577,
          "mem": 14018,
          "gpus": 0,
          "cpus": 4,
          "ports": "[1-21, 23-5050, 5052-32000]"
        }
      },
      "unreserved_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "attributes": {
        "public_ip": "true"
      },
      "active": true,
      "version": "1.2.0",
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "TASK_RUNNING": 0,
      "TASK_KILLING": 0,
      "TASK_FINISHED": 0,
      "TASK_KILLED": 0,
      "TASK_FAILED": 0,
      "TASK_LOST": 0,
      "TASK_ERROR": 0,
      "framework_ids": []
    }
  ],
  "frameworks": [
    {
      "id": "74f1836b-6784-4030-816e-aacbdd45ff57-0002",
      "name": "confluent-kafka",
      "pid": "scheduler-d1c33942-e677-40b5-87fb-f36885359263@10.0.2.121:44347",
      "used_resources": {
        "disk": 5000,
        "mem": 2560,
        "gpus": 0,
        "cpus": 1.5,
        "ports": "[1025-1025, 9234-9234]"
      },
      "offered_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "capabilities": [],
      "hostname": "ip-10-0-2-121.us-west-2.compute.internal",
      "webui_url": "",
      "active": true,
      "connected": true,
      "recovered": false,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "TASK_RUNNING": 1,
      "TASK_KILLING": 0,
      "TASK_FINISHED": 0,
      "TASK_KILLED": 0,
      "TASK_FAILED": 0,
      "TASK_LOST": 0,
      "TASK_ERROR": 0,
      "slave_ids": ["74f1836b-6784-4030-816e-aacbdd45ff57-S1"]
    },
    {
      "id": "74f1836b-6784-4030-816e-aacbdd45ff57-0001",
      "name": "marathon",
      "pid": "scheduler-2210a7de-5ddd-425e-a888-b36e3f372cec@10.0.4.58:45121",
      "used_resources": {
        "disk": 0,
        "mem": 1262,
        "gpus": 0,
        "cpus": 1.01,
        "ports": "[24348-24349, 29557-29557]"
      },
      "offered_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "capabilities": ["TASK_KILLING_STATE", "PARTITION_AWARE"],
      "hostname": "10.0.4.58",
      "webui_url": "https://10.0.4.58:8443",
      "active": true,
      "connected": true,
      "recovered": false,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "TASK_RUNNING": 2,
      "TASK_KILLING": 0,
      "TASK_FINISHED": 0,
      "TASK_KILLED": 0,
      "TASK_FAILED": 0,
      "TASK_LOST": 0,
      "TASK_ERROR": 0,
      "slave_ids": ["74f1836b-6784-4030-816e-aacbdd45ff57-S1"]
    },
    {
      "id": "74f1836b-6784-4030-816e-aacbdd45ff57-0000",
      "name": "metronome",
      "pid": "scheduler-eeefee3d-ffd9-429f-9057-17e9290b995d@10.0.4.58:41263",
      "used_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "offered_resources": {
        "disk": 0,
        "mem": 0,
        "gpus": 0,
        "cpus": 0
      },
      "capabilities": [],
      "hostname": "10.0.4.58",
      "webui_url": "http://10.0.4.58:9090",
      "active": true,
      "connected": true,
      "recovered": false,
      "TASK_STAGING": 0,
      "TASK_STARTING": 0,
      "TASK_RUNNING": 0,
      "TASK_KILLING": 0,
      "TASK_FINISHED": 0,
      "TASK_KILLED": 0,
      "TASK_FAILED": 0,
      "TASK_LOST": 0,
      "TASK_ERROR": 0,
      "slave_ids": []
    }
  ]
}
